# Generated by Django 4.1.7 on 2023-03-24 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='message',
            field=models.TextField(default='null', verbose_name='Mensaje'),
        ),
    ]
